# ref: https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node: [ 12, 14, 16, 18 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
